name: Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Pull
      uses: actions/checkout@v2
    - name: Install .Net Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        source-url: https://nuget.pkg.github.com/sensemaking/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build and Test
      run: dotnet build --configuration Release
    - name: Package
      run: dotnet pack -o packages --no-restore
    - name: Publish Packages 
      run: dotnet nuget push ${{ github.workspace }}\packages\*.nupkg 